import './globals.css'
import StepProvider from './context/step-provider'




export const metadata = {
  title: 'reservation',
  description: 'Generated by create  Mohammadreza'
}

export default function RootLayout ({ children }) {
  return (
    <html lang='en'>
      <StepProvider>
        <body className='flex flex-col gap-5 h-screen'>{children}</body>
      </StepProvider>
    </html>
  )
}
